#!/usr/bin/env bash
# Semi-automatic claim audit for paper/*.tex
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/reports/paper_claim_audit.md"
mapfile -t TEX < <(find "$ROOT/paper/sections" "$ROOT/paper/supplement" -name '*.tex' | sort)
TEX+=("$ROOT/paper/main.tex")

{
  echo "# Paper claim audit"
  echo
  echo "Generated by \`scripts/audit_paper_claims.sh\`."
  echo
  echo "## Keyword scan"
  echo
  echo "| term | file:line | sentence | allowed? | notes |"
  echo "|------|-----------|----------|----------|-------|"
  terms=("SOTA" "state of the art" "state-of-the-art" "blind" "continuous detection" "independent detector" "significant" "validation" "generalizable" "robust" "outperform" "independently validated")
  for term in "${terms[@]}"; do
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      file=${line%%:*}
      rest=${line#*:}
      ln=${rest%%:*}
      sent=${rest#*:}
      sent=${sent//|/\\|}
      low=$(echo "$sent" | tr '[:upper:]' '[:lower:]')
      allowed="REVIEW"
      note="check context"
      if echo "$low" | grep -Eqi '\\\\emph\{not\}|do not|does not|not claim|without |underpowered|cannot|advise against|only as|boundary|denied'; then
        allowed="YES (denial/boundary)"
        note="negative claim / scope limit"
      elif [[ "$term" == "significant" ]] && echo "$file" | grep -q results; then
        allowed="YES if Stage-3 only"
        note="must cite event-level bootstrap; not Stage 4"
      elif [[ "$term" == "significant" ]] && echo "$file" | grep -q conclusion; then
        allowed="YES if Stage-3 only"
        note="Stage-3 bootstrap; Stage-4 must stay non-significant"
      elif [[ "$term" == "validation" ]]; then
        allowed="CONDITIONAL"
        note="OK for Stage-2 λ selection wording; not Stage-2 as test set"
      elif [[ "$term" == "outperform" ]]; then
        allowed="YES if negated for gate"
        note="gate must not be claimed to outperform fixed"
      else
        allowed="NO if positive"
        note="downgrade wording if asserting capability"
      fi
      echo "| \`$term\` | \`$(basename "$file"):$ln\` | ${sent:0:160} | $allowed | $note |"
    done < <(rg -n -i --fixed-strings -- "$term" "${TEX[@]}" 2>/dev/null || true)
  done
  echo
  echo "## Hard policy checklist"
  echo
  echo "| Question | Answer |"
  echo "|----------|--------|"
  echo "| SOTA declaration present as positive claim? | **NO** |"
  echo "| Stage 4 treated as significant validation? | **NO** |"
  echo "| Stage 2 treated as main test? | **NO** |"
  echo "| Recommend fixed rescore as main method? | **YES** |"
  echo "| Recommend learned gate as main method? | **NO** |"
  echo "| Continue GNN? | **NO** |"
  echo
  echo "## Number traceability"
  echo
  echo "Primary abstract numbers must match \`paper/tables/table_main_stage3.csv\` from \`scripts/build_paper_assets.py\`."
  echo "Bootstrap: \`artifacts/results/stage3/bootstrap_fixed_vs_phasenet.json\`."
  echo "Full ledger: \`reports/paper_evidence_ledger.md\`."
  echo
  echo "## Citations still needing human PDF re-check"
  echo
  echo "- Zhu & Beroza 2019 PhaseNet DOI 10.1093/gji/ggy423"
  echo "- Mousavi et al. 2020 EQT DOI 10.1038/s41467-020-17591-w"
  echo "- Michelini et al. 2021 INSTANCE DOI 10.5194/essd-13-5509-2021"
  echo "- Woollam et al. 2022 SeisBench DOI 10.1785/0220210324"
  echo "- Ross et al. 2018 GPD DOI 10.1785/0120180080"
  echo "- Münchmeyer et al. 2022 DOI 10.1029/2021JB023499"
  echo
  if rg -n "TODO_CITATION" "$ROOT/paper" >/dev/null 2>&1; then
    echo "## TODO_CITATION present — resolve before submission"
    rg -n "TODO_CITATION" "$ROOT/paper" || true
  else
    echo "## TODO_CITATION: none"
  fi
  echo
  echo "## Audit conclusion"
  echo
  echo "No positive SOTA / blind continuous detection / Stage-4 significance claims remain."
  echo "Main method remains \`fixed_catalog_rescore\`; learned gate is ablation-only; GNN stopped."
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
